/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ethp.barrenland.main.model;

import static org.junit.Assert.assertEquals;

import java.util.HashSet;
import java.util.Set;

import org.junit.Test;

public class LandTest {
	
    private static final int LAND_WIDTH = 400;
    private static final int LAND_HEIGHT = 600;
    
	@Test
	public void testSimpleConstructor() {
		Land land = new Land(400, 600);
		final int TOTAL_AREA = LAND_WIDTH * LAND_HEIGHT;
		assertEquals(TOTAL_AREA, land.getArea());
		assertEquals(TOTAL_AREA, land.getTotalFertileArea());
		assertEquals(0, land.getTotalBarrenArea());
	}
	
	@Test
	public void testBarrenAreaConstructor() {
		Rectangle barrenArea = new Rectangle(0, 292, 399, 307);
		
        Set<Rectangle> barrentAreas = new HashSet<>();
        barrentAreas.add(barrenArea);
		
		Land land = new Land(400, 600, barrentAreas);
		final int TOTAL_AREA = LAND_WIDTH * LAND_HEIGHT;
		assertEquals(TOTAL_AREA, land.getArea());
		assertEquals(TOTAL_AREA - barrenArea.getArea(), land.getTotalFertileArea());
		assertEquals(barrenArea.getArea(), land.getTotalBarrenArea());
	}

}
